-- Seed popular canonical laboratory tests for offline matching, SEO, and future provider ingestion.
-- This migration only updates the canonical taxonomy. It does not write provider prices.

insert into public.canonical_tests (
  code,
  name_ru,
  name_en,
  kind,
  category,
  aliases,
  description,
  is_active,
  raw_payload
)
values
  ('ALT', 'АЛТ', 'Alanine aminotransferase', 'analysis', 'biochemistry/liver', array['алт','аланинаминотрансфераза','аланин аминотрансфераза','alt','alat'], 'Популярный биохимический показатель. Используется для сравнения цен, не является медицинской рекомендацией.', true, '{"seed":"popular_canonical_tests_v1"}'::jsonb),
  ('AST', 'АСТ', 'Aspartate aminotransferase', 'analysis', 'biochemistry/liver', array['аст','аспартатаминотрансфераза','аспартат аминотрансфераза','ast','asat'], 'Популярный биохимический показатель. Используется для сравнения цен, не является медицинской рекомендацией.', true, '{"seed":"popular_canonical_tests_v1"}'::jsonb),
  ('BILT', 'Билирубин общий', 'Total bilirubin', 'analysis', 'biochemistry/liver', array['билирубин общий','общий билирубин','total bilirubin'], 'Популярный биохимический показатель. Используется для сравнения цен, не является медицинской рекомендацией.', true, '{"seed":"popular_canonical_tests_v1"}'::jsonb),
  ('BILD', 'Билирубин прямой', 'Direct bilirubin', 'analysis', 'biochemistry/liver', array['билирубин прямой','прямой билирубин','direct bilirubin'], 'Популярный биохимический показатель. Используется для сравнения цен, не является медицинской рекомендацией.', true, '{"seed":"popular_canonical_tests_v1"}'::jsonb),
  ('GGT', 'ГГТ', 'Gamma-glutamyl transferase', 'analysis', 'biochemistry/liver', array['ггт','гамма гт','гамма-гт','гамма глутамилтрансфераза','ggt','gamma gt'], 'Популярный биохимический показатель. Используется для сравнения цен, не является медицинской рекомендацией.', true, '{"seed":"popular_canonical_tests_v1"}'::jsonb),
  ('ALP', 'Щелочная фосфатаза', 'Alkaline phosphatase', 'analysis', 'biochemistry/liver', array['щелочная фосфатаза','alkaline phosphatase','alp','щф'], 'Популярный биохимический показатель. Используется для сравнения цен, не является медицинской рекомендацией.', true, '{"seed":"popular_canonical_tests_v1"}'::jsonb),
  ('TP', 'Белок общий', 'Total protein', 'analysis', 'biochemistry/protein', array['белок общий','общий белок','total protein'], 'Популярный биохимический показатель. Используется для сравнения цен, не является медицинской рекомендацией.', true, '{"seed":"popular_canonical_tests_v1"}'::jsonb),
  ('ALB', 'Альбумин', 'Albumin', 'analysis', 'biochemistry/protein', array['альбумин','albumin'], 'Популярный биохимический показатель. Используется для сравнения цен, не является медицинской рекомендацией.', true, '{"seed":"popular_canonical_tests_v1"}'::jsonb),
  ('UREA', 'Мочевина', 'Urea', 'analysis', 'kidney', array['мочевина','urea'], 'Популярный показатель функции почек. Используется для сравнения цен, не является медицинской рекомендацией.', true, '{"seed":"popular_canonical_tests_v1"}'::jsonb),
  ('UA_ACID', 'Мочевая кислота', 'Uric acid', 'analysis', 'biochemistry/kidney', array['мочевая кислота','uric acid'], 'Популярный биохимический показатель. Используется для сравнения цен, не является медицинской рекомендацией.', true, '{"seed":"popular_canonical_tests_v1"}'::jsonb),
  ('CRP', 'С-реактивный белок', 'C-reactive protein', 'analysis', 'inflammation', array['с реактивный белок','с-реактивный белок','срб','crp','c reactive protein'], 'Популярный маркер воспаления. Используется для сравнения цен, не является медицинской рекомендацией.', true, '{"seed":"popular_canonical_tests_v1"}'::jsonb),
  ('ESR', 'СОЭ', 'Erythrocyte sedimentation rate', 'analysis', 'hematology', array['соэ','скорость оседания эритроцитов','esr'], 'Популярный гематологический показатель. Используется для сравнения цен, не является медицинской рекомендацией.', true, '{"seed":"popular_canonical_tests_v1"}'::jsonb),
  ('HBA1C', 'Гликированный гемоглобин', 'HbA1c', 'analysis', 'diabetes', array['гликированный гемоглобин','гликозилированный гемоглобин','hba1c','hb a1c','гемоглобин a1c'], 'Популярный показатель углеводного обмена. Используется для сравнения цен, не является медицинской рекомендацией.', true, '{"seed":"popular_canonical_tests_v1"}'::jsonb),
  ('INS', 'Инсулин', 'Insulin', 'analysis', 'diabetes/hormones', array['инсулин','insulin'], 'Популярный гормональный показатель. Используется для сравнения цен, не является медицинской рекомендацией.', true, '{"seed":"popular_canonical_tests_v1"}'::jsonb),
  ('FT4', 'Т4 свободный', 'Free thyroxine', 'analysis', 'thyroid', array['т4 свободный','свободный т4','тироксин свободный','free t4','ft4'], 'Популярный тиреоидный показатель. Используется для сравнения цен, не является медицинской рекомендацией.', true, '{"seed":"popular_canonical_tests_v1"}'::jsonb),
  ('FT3', 'Т3 свободный', 'Free triiodothyronine', 'analysis', 'thyroid', array['т3 свободный','свободный т3','трийодтиронин свободный','free t3','ft3'], 'Популярный тиреоидный показатель. Используется для сравнения цен, не является медицинской рекомендацией.', true, '{"seed":"popular_canonical_tests_v1"}'::jsonb),
  ('AT_TPO', 'Антитела к ТПО', 'Anti-thyroid peroxidase antibodies', 'analysis', 'thyroid', array['антитела к тпо','ат к тпо','анти тпо','anti tpo','anti-tpo','антитела к тиреопероксидазе'], 'Популярный тиреоидный иммунологический показатель. Используется для сравнения цен, не является медицинской рекомендацией.', true, '{"seed":"popular_canonical_tests_v1"}'::jsonb),
  ('AT_TG', 'Антитела к тиреоглобулину', 'Anti-thyroglobulin antibodies', 'analysis', 'thyroid', array['антитела к тиреоглобулину','ат к тг','анти тг','anti tg','anti-thyroglobulin'], 'Популярный тиреоидный иммунологический показатель. Используется для сравнения цен, не является медицинской рекомендацией.', true, '{"seed":"popular_canonical_tests_v1"}'::jsonb),
  ('B12', 'Витамин B12', 'Vitamin B12', 'analysis', 'vitamins', array['витамин b12','витамин в12','цианокобаламин','vitamin b12','b12'], 'Популярный витаминный показатель. Используется для сравнения цен, не является медицинской рекомендацией.', true, '{"seed":"popular_canonical_tests_v1"}'::jsonb),
  ('FOL', 'Фолиевая кислота', 'Folate', 'analysis', 'vitamins', array['фолиевая кислота','фолат','folate','folic acid'], 'Популярный витаминный показатель. Используется для сравнения цен, не является медицинской рекомендацией.', true, '{"seed":"popular_canonical_tests_v1"}'::jsonb),
  ('IRON', 'Железо', 'Serum iron', 'analysis', 'iron', array['железо','сывороточное железо','iron','serum iron'], 'Популярный показатель обмена железа. Используется для сравнения цен, не является медицинской рекомендацией.', true, '{"seed":"popular_canonical_tests_v1"}'::jsonb),
  ('TRF', 'Трансферрин', 'Transferrin', 'analysis', 'iron', array['трансферрин','transferrin'], 'Популярный показатель обмена железа. Используется для сравнения цен, не является медицинской рекомендацией.', true, '{"seed":"popular_canonical_tests_v1"}'::jsonb),
  ('MG', 'Магний', 'Magnesium', 'analysis', 'minerals', array['магний','magnesium','mg'], 'Популярный минеральный показатель. Используется для сравнения цен, не является медицинской рекомендацией.', true, '{"seed":"popular_canonical_tests_v1"}'::jsonb),
  ('CA', 'Кальций общий', 'Total calcium', 'analysis', 'minerals', array['кальций общий','общий кальций','calcium total','total calcium'], 'Популярный минеральный показатель. Используется для сравнения цен, не является медицинской рекомендацией.', true, '{"seed":"popular_canonical_tests_v1"}'::jsonb),
  ('NA', 'Натрий', 'Sodium', 'analysis', 'electrolytes', array['натрий','sodium','na'], 'Популярный электролит. Используется для сравнения цен, не является медицинской рекомендацией.', true, '{"seed":"popular_canonical_tests_v1"}'::jsonb),
  ('K', 'Калий', 'Potassium', 'analysis', 'electrolytes', array['калий','potassium','k'], 'Популярный электролит. Используется для сравнения цен, не является медицинской рекомендацией.', true, '{"seed":"popular_canonical_tests_v1"}'::jsonb),
  ('CL', 'Хлор', 'Chloride', 'analysis', 'electrolytes', array['хлор','хлориды','chloride','chlorides','cl'], 'Популярный электролит. Используется для сравнения цен, не является медицинской рекомендацией.', true, '{"seed":"popular_canonical_tests_v1"}'::jsonb),
  ('TG', 'Триглицериды', 'Triglycerides', 'analysis', 'lipids', array['триглицериды','triglycerides','tg'], 'Популярный липидный показатель. Используется для сравнения цен, не является медицинской рекомендацией.', true, '{"seed":"popular_canonical_tests_v1"}'::jsonb),
  ('HDL', 'ЛПВП', 'HDL cholesterol', 'analysis', 'lipids', array['лпвп','холестерин лпвп','липопротеины высокой плотности','hdl','hdl cholesterol'], 'Популярный липидный показатель. Используется для сравнения цен, не является медицинской рекомендацией.', true, '{"seed":"popular_canonical_tests_v1"}'::jsonb),
  ('LDL', 'ЛПНП', 'LDL cholesterol', 'analysis', 'lipids', array['лпнп','холестерин лпнп','липопротеины низкой плотности','ldl','ldl cholesterol'], 'Популярный липидный показатель. Используется для сравнения цен, не является медицинской рекомендацией.', true, '{"seed":"popular_canonical_tests_v1"}'::jsonb),
  ('PRL', 'Пролактин', 'Prolactin', 'analysis', 'hormones/reproductive', array['пролактин','prolactin'], 'Популярный гормональный показатель. Используется для сравнения цен, не является медицинской рекомендацией.', true, '{"seed":"popular_canonical_tests_v1"}'::jsonb),
  ('E2', 'Эстрадиол', 'Estradiol', 'analysis', 'hormones/reproductive', array['эстрадиол','estradiol','e2'], 'Популярный гормональный показатель. Используется для сравнения цен, не является медицинской рекомендацией.', true, '{"seed":"popular_canonical_tests_v1"}'::jsonb),
  ('PROG', 'Прогестерон', 'Progesterone', 'analysis', 'hormones/reproductive', array['прогестерон','progesterone'], 'Популярный гормональный показатель. Используется для сравнения цен, не является медицинской рекомендацией.', true, '{"seed":"popular_canonical_tests_v1"}'::jsonb),
  ('TESTO', 'Тестостерон общий', 'Total testosterone', 'analysis', 'hormones/reproductive', array['тестостерон общий','общий тестостерон','total testosterone','testosterone'], 'Популярный гормональный показатель. Используется для сравнения цен, не является медицинской рекомендацией.', true, '{"seed":"popular_canonical_tests_v1"}'::jsonb),
  ('LH', 'ЛГ', 'Luteinizing hormone', 'analysis', 'hormones/reproductive', array['лг','лютеинизирующий гормон','luteinizing hormone','lh'], 'Популярный гормональный показатель. Используется для сравнения цен, не является медицинской рекомендацией.', true, '{"seed":"popular_canonical_tests_v1"}'::jsonb),
  ('FSH', 'ФСГ', 'Follicle-stimulating hormone', 'analysis', 'hormones/reproductive', array['фсг','фолликулостимулирующий гормон','follicle stimulating hormone','fsh'], 'Популярный гормональный показатель. Используется для сравнения цен, не является медицинской рекомендацией.', true, '{"seed":"popular_canonical_tests_v1"}'::jsonb),
  ('HCG', 'ХГЧ', 'Human chorionic gonadotropin', 'analysis', 'hormones/pregnancy', array['хгч','бета хгч','β хгч','хорионический гонадотропин','hcg','beta hcg'], 'Популярный гормональный показатель. Используется для сравнения цен, не является медицинской рекомендацией.', true, '{"seed":"popular_canonical_tests_v1"}'::jsonb),
  ('PSA_T', 'ПСА общий', 'Total PSA', 'analysis', 'tumor_markers', array['пса общий','общий пса','простатический специфический антиген общий','psa total','total psa'], 'Популярный онкомаркер/скрининговый показатель. Используется для сравнения цен, не является медицинской рекомендацией.', true, '{"seed":"popular_canonical_tests_v1"}'::jsonb),
  ('DDIMER', 'D-димер', 'D-dimer', 'analysis', 'coagulation', array['d димер','d-димер','д димер','д-димер','d-dimer','ddimer'], 'Популярный показатель гемостаза. Используется для сравнения цен, не является медицинской рекомендацией.', true, '{"seed":"popular_canonical_tests_v1"}'::jsonb),
  ('COAG', 'Коагулограмма', 'Coagulation panel', 'panel', 'coagulation', array['коагулограмма','гемостазиограмма','анализ свертываемости крови','coagulation panel'], 'Популярный комплекс показателей гемостаза. Используется для сравнения цен, не является медицинской рекомендацией.', true, '{"seed":"popular_canonical_tests_v1"}'::jsonb),
  ('LIPID', 'Липидный профиль', 'Lipid profile', 'panel', 'lipids', array['липидный профиль','липидограмма','lipid profile','липидный спектр'], 'Популярный комплекс липидного обмена. Используется для сравнения цен, не является медицинской рекомендацией.', true, '{"seed":"popular_canonical_tests_v1"}'::jsonb),
  ('THYROID_BASIC', 'Щитовидная железа базовый профиль', 'Basic thyroid profile', 'panel', 'thyroid', array['щитовидная железа базовый профиль','тиреоидный профиль','профиль щитовидной железы','ттг т4 свободный','thyroid profile'], 'Популярный тиреоидный комплекс. Используется для сравнения цен, не является медицинской рекомендацией.', true, '{"seed":"popular_canonical_tests_v1"}'::jsonb)
on conflict (code) do update
set
  name_ru = excluded.name_ru,
  name_en = excluded.name_en,
  kind = excluded.kind,
  category = excluded.category,
  aliases = excluded.aliases,
  description = excluded.description,
  is_active = excluded.is_active,
  raw_payload = coalesce(public.canonical_tests.raw_payload, '{}'::jsonb) || excluded.raw_payload,
  updated_at = now();

insert into public.clinical_services (
  canonical_test_id,
  code,
  name_ru,
  name_en,
  service_kind,
  domain,
  seo_slug,
  city_landing_enabled,
  is_active,
  raw_payload
)
select
  canonical.id,
  seed.code,
  canonical.name_ru,
  canonical.name_en,
  case when canonical.kind in ('panel','profile') then 'lab_panel' else 'lab_test' end,
  seed.domain,
  seed.seo_slug,
  true,
  true,
  '{"seed":"popular_canonical_tests_v1","bridge":"canonical_test_to_service"}'::jsonb
from public.canonical_tests canonical
join (
  values
    ('ALT', 'alt', 'human'),
    ('AST', 'ast', 'human'),
    ('BILT', 'bilirubin-total', 'human'),
    ('BILD', 'bilirubin-direct', 'human'),
    ('GGT', 'ggt', 'human'),
    ('ALP', 'alkaline-phosphatase', 'human'),
    ('TP', 'total-protein', 'human'),
    ('ALB', 'albumin', 'human'),
    ('UREA', 'urea', 'human'),
    ('UA_ACID', 'uric-acid', 'human'),
    ('CRP', 'crp', 'human'),
    ('ESR', 'esr', 'human'),
    ('HBA1C', 'hba1c', 'human'),
    ('INS', 'insulin', 'human'),
    ('FT4', 'free-t4', 'human'),
    ('FT3', 'free-t3', 'human'),
    ('AT_TPO', 'anti-tpo', 'human'),
    ('AT_TG', 'anti-thyroglobulin', 'human'),
    ('B12', 'vitamin-b12', 'human'),
    ('FOL', 'folate', 'human'),
    ('IRON', 'iron', 'human'),
    ('TRF', 'transferrin', 'human'),
    ('MG', 'magnesium', 'human'),
    ('CA', 'calcium-total', 'human'),
    ('NA', 'sodium', 'human'),
    ('K', 'potassium', 'human'),
    ('CL', 'chloride', 'human'),
    ('TG', 'triglycerides', 'human'),
    ('HDL', 'hdl-cholesterol', 'human'),
    ('LDL', 'ldl-cholesterol', 'human'),
    ('PRL', 'prolactin', 'human'),
    ('E2', 'estradiol', 'human'),
    ('PROG', 'progesterone', 'human'),
    ('TESTO', 'testosterone-total', 'human'),
    ('LH', 'lh', 'human'),
    ('FSH', 'fsh', 'human'),
    ('HCG', 'hcg', 'human'),
    ('PSA_T', 'psa-total', 'human'),
    ('DDIMER', 'd-dimer', 'human'),
    ('COAG', 'coagulogram', 'human'),
    ('LIPID', 'lipid-profile', 'human'),
    ('THYROID_BASIC', 'thyroid-basic-profile', 'human')
) as seed(code, seo_slug, domain)
  on canonical.code = seed.code
on conflict (code) do update
set
  canonical_test_id = excluded.canonical_test_id,
  name_ru = excluded.name_ru,
  name_en = excluded.name_en,
  service_kind = excluded.service_kind,
  domain = excluded.domain,
  seo_slug = excluded.seo_slug,
  city_landing_enabled = excluded.city_landing_enabled,
  is_active = excluded.is_active,
  raw_payload = coalesce(public.clinical_services.raw_payload, '{}'::jsonb) || excluded.raw_payload,
  updated_at = now();
